### ISSUE TITLE
cant replicated mnist_100_full

### ISSUE THREAD

**Issue by youralien** [arasmus/ladder#1]
When running the command for mnist_100_full,
```
# Full
run.py train --encoder-layers 1000-500-250-250-250-10 --decoder-spec sig --denoising-cost-x 1000,10,0.1,0.1,0.1,0.1,0.1 --labeled-samples 100 --unlabeled-samples 60000 --seed 1 -- mnist_100_full
```

I get 16.7% error, which is nothing close to the 1.13% reported in the paper.

**Comment by arasmus** [comment]
The problem is most likely in the way Fuel converts MNIST data. It should convert it to ```float32``` to work. If it is in ```unsigned int``` format, it doesn't work. Could that be the cause? Some people had this problem.

If you make sure you use Fuel from tag v0.0.1 and use the command specified in the readme, it should work.

**Comment by youralien** [comment]
Thank you for your quick response!  I did some debugging and it indeed was the case that the features were not in the ```0 - 1``` range.  Now, I am getting 1.1% error! :bulb:
