### ISSUE TITLE
ValueError: '['train']' split is not provided by this dataset. Available splits are (u'test', u'train').

### ISSUE THREAD

**Issue by tongmuyuan** [arasmus/ladder#18]
Hi, I just setup the environment, and got a issue in my first running. Could you please show me how to solve this problem, many thanks!!!

$ python run.py train --encoder-layers 1000-500-250-250-250-10 --decoder-spec gauss --denoising-cost-x 2000,20,0.1,0.1,0.1,0.1,0.1 --labeled-samples 50 --unlabeled-samples 60000 --seed 1 -- mnist_50_full

INFO:main:Logging into results/mnist_50_full6/log.txt
INFO:main:== COMMAND LINE ==
INFO:main:run.py train --encoder-layers 1000-500-250-250-250-10 --decoder-spec gauss --denoising-cost-x 2000,20,0.1,0.1,0.1,0.1,0.1 --labeled-samples 50 --unlabeled-samples 60000 --seed 1 -- mnist_50_full
INFO:main:== PARAMETERS ==
INFO:main: zestbn              : bugfix  
INFO:main: dseed               : 1  
INFO:main: top_c               : 1  
INFO:main: super_noise_std     : 0.3  
INFO:main: batch_size          : 100  
INFO:main: dataset             : mnist  
INFO:main: valid_set_size      : 10000  
INFO:main: num_epochs          : 150  
INFO:main: whiten_zca          : 0  
INFO:main: unlabeled_samples   : 60000  
INFO:main: decoder_spec        : ('gauss',)  
INFO:main: valid_batch_size    : 100  
INFO:main: denoising_cost_x    : (2000.0, 20.0, 0.1, 0.1, 0.1, 0.1, 0.1) 
INFO:main: f_local_noise_std   : 0.3  
INFO:main: cmd                 : train  
INFO:main: act                 : relu  
INFO:main: lrate_decay         : 0.67  
INFO:main: seed                : 1  
INFO:main: lr                  : 0.002  
INFO:main: save_to             : mnist_50_full  
INFO:main: save_dir            : results/mnist_50_full6 
INFO:main: commit              : 5a8daa1760535ec4aa25c20c531e1cc31c76d911 
INFO:main: contrast_norm       : 0  
INFO:main: encoder_layers      : ('1000', '500', '250', '250', '250', '10') 
INFO:main: labeled_samples     : 50  
Traceback (most recent call last):
File "run.py", line 656, in <module>
    if train(d) is None:
  File "run.py", line 410, in train
    in_dim, data, whiten, cnorm = setup_data(p, test_set=False)
  File "run.py", line 245, in setup_data
    train_set = dataset_class(["train"])
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/mnist.py", line 36, in **init**
    super(MNIST, self).**init**(self.data_path, which_set, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 146, in **init**
    "{}.".format(self.available_splits))
ValueError: '['train']' split is not provided by this dataset. Available splits are (u'test', u'train').

**Comment by hotloo** [comment]
Thanks for the interest in our work! Could you post your python dependency here? We are using Fuel 0.2 and it could be that the version did not match. Cheers!

**Comment by tongmuyuan** [comment]
@hotloo thanks for reply, I just solve this problem by:
replace "     train_set = dataset_class("[train]") " in run.py to "train_set = dataset_class("train")"

but I still got another question: when I finished install anaconda, and type:
                "julian@PremilabServer02:~/myproject/ladder$ **conda env create -f environment.yml** " 
to command window, it shows that: 
                       "conda: command not found" 
what should I do?    really thanks appreciate for your help, many thanks!!

**Comment by hotloo** [comment]
@tongmuyuan OK. The best place to check the latest installation of Anaconda is at https://www.continuum.io/downloads

However, it looks like that your conda is not added the $PATH. A simple search on Google gave me this. Could you try this out? 

http://stackoverflow.com/questions/35246386/conda-command-not-found

**Comment by tongmuyuan** [comment]
@hotloo  Thank you very much, it helps me to added conda to $PATH. funny things is that, the iron-wall in my country blocked the second webside you gave to me, and I had to use a VPN for connection. anyway, you solved my question, thank you.

**Comment by hotloo** [comment]
Good that we did solve the immediate issue. I will close this one now.
