### ISSUE TITLE
What's the meaning of the symbols in the results?

### ISSUE THREAD

**Issue by yangohuang** [arasmus/ladder#27]
I have run the code using 100 labeled samples 10000 labeled validation 50000 unlabele on my GPU.
Here is the results:

Saving to results/mnist_100_full0/trained_params
e 150, i 90000:V_C_class nan, V_E nan, V_C_de nan nan nan nan nan nan nan, T_C_de 0.00541 0.0612 0.922 0.351 0.159 0.0551 0.0312, T_C_class 0.000315, VF_C_class nan, VF_E nan, VF_C_de nan nan nan nan nan nan nan
valid_final_error_rate_clean nan
Took 130.8 minutes

What is the meaning of V_C T_C etc.?
Thanks.

**Comment by hotloo** [comment]
Hi! Better late than never! 

V_C_class is validation classification cost, 
V_C_de is validation denoising cost,
T_C_de training denoising cost
T_C_class training classification cost
VF_E validation final error
VF_C_de validation final denoising cost

Hope this helps!
